### ISSUE TITLE
页面管理新增页面之后，在修改属性报错

### ISSUE THREAD

**Issue by gongchao** [medz/fans#102]
![img](http://p1.bqimg.com/4851/6192df31080f5d83.jpg)

**Comment by medz** [comment]
请吧下面红色部分文字复制到issue中～

**Comment by gongchao** [comment]
@medz 
Too few arguments to function PwDesignThreadDataService::decorateSaveProperty(), 1 passed in /opt/site/forum/src/applications/design/admin/PropertyController.php on line 218 and exactly 2 expected

**Comment by medz** [comment]
好的～ 我本地测试下～
