### ISSUE TITLE
能否转用 PHPMailer 发送邮件？

### ISSUE THREAD

**Issue by Sefank** [medz/fans#103]
Windframework 框架采用的邮件发送方式十分繁杂，而且只支持在 php.ini 配置好SMTP后才可以发送邮件。所以问一下能否将邮件系统改用 PHPMailer ？

**Comment by medz** [comment]
这部分后续会替换～

**Comment by Sefank** [comment]
好的，期待ing

**Comment by wzzjhc** [comment]
目前先用QQ企业代替吧
