### ISSUE TITLE
全选 分类出错

### ISSUE THREAD

**Issue by phpbjr** [medz/fans#110]
![2014](https://cloud.githubusercontent.com/assets/26362034/23832677/89563c66-0774-11e7-8a5e-836d8b64bfe1.png)
全选 分类出错
Uncaught error with message 'Cannot use object of type PwError as array'

The server encountered an internal error and failed to process your request. Please try again later. If this error is temporary, reloading the page might resolve the problem. 
If you are able to contact the administrator report this error message.(http://www.windframework.com/)

**Comment by medz** [comment]
收到，会抽时间排查。

Seven Du <lovevipdsw@outlook.com<mailto:lovevipdsw@outlook.com>>

在 2017年3月12日，22:41，phpbjr <notifications@github.com<mailto:notifications@github.com>> 写道：


[2014]<https://cloud.githubusercontent.com/assets/26362034/23832677/89563c66-0774-11e7-8a5e-836d8b64bfe1.png>
全选 分类出错
Uncaught error with message 'Cannot use object of type PwError as array'

The server encountered an internal error and failed to process your request. Please try again later. If this error is temporary, reloading the page might resolve the problem.
If you are able to contact the administrator report this error message.(http://www.windframework.com/)
