### ISSUE TITLE
几条建议，请关注，谢谢

### ISSUE THREAD

**Issue by xmlf** [medz/fans#134]
1、能否在后台加入“地区白名单“功能？管理员在输入地区名，系统通过IP来源判断是否包含，包含就不需要邀请注册或邮箱激活，不包含就需要邀请注册或邮箱激活等。
一直没有升9.0是因为这个问题一直没人解决，http://www.phpwind.net/read/2974872
2、IP禁止目前效果不好，能否改为地区禁止？同上
3、可否加入语音发帖功能？这个技术不难，用起来很牛逼，增强活跃度很关键

**Comment by medz** [comment]
感谢建议，但是鉴于1.1的开发问题，后续酌情添加。

Seven Du <lovevipdsw@outlook.com<mailto:lovevipdsw@outlook.com>>

在 2017年3月29日，15:50，xmlf <notifications@github.com<mailto:notifications@github.com>> 写道：


1、能否在后台加入“地区白名单“功能？管理员在输入地区名，系统通过IP来源判断是否包含，包含就不需要邀请注册或邮箱激活，不包含就需要邀请注册或邮箱激活等。
一直没有升9.0是因为这个问题一直没人解决，http://www.phpwind.net/read/2974872
2、IP禁止目前效果不好，能否改为地区禁止？同上
3、可否加入语音发帖功能？这个技术不难，用起来很牛逼，增强活跃度很关键
