### ISSUE TITLE
我从dz转到pw发现用户密码没有一个可以登录的

### ISSUE THREAD

**Issue by jkjoy** [medz/fans#147]
用密码找回功能也不能更改 密码。请问有什么办法可以解决吗

**Comment by medz** [comment]
额～这个是pwf

**Comment by jkjoy** [comment]
额 我就是转换且升级为pwf了

**Comment by medz** [comment]
这说明你转pw的时候就没法登陆了。

Seven Du <lovevipdsw@outlook.com<mailto:lovevipdsw@outlook.com>>

在 2017年4月29日，17:02，sunpeiwen <notifications@github.com<mailto:notifications@github.com>> 写道：


额 我就是转换且升级为pwf了

**Comment by jkjoy** [comment]
貌似是因为加密方式不一样？
