### ISSUE TITLE
8.7升级到1.0.10问题

### ISSUE THREAD

**Issue by xmlf** [medz/fans#238]
是不是8.7 gbk升级到 9.0（20130702）utf8版本后，直接可以升级到fans 1.0.10？
还是要先升级到1.0.9？
升级方法是直接把文件覆盖吗？

**Comment by beautifultable** [comment]
8.7需要先升级到官方9.0版本，确认没有问题后直接将Fans 1.0.10覆盖即可，请做好备份。
