### ISSUE TITLE
全局置顶主题，重复出现

### ISSUE THREAD

**Issue by lkddi** [medz/fans#259]
本站新帖列表及 一级板块列表内，置顶帖子会重复出现。

**Comment by medz** [comment]
不是提过了呢？

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月2日，13:10，->流星 <notifications@github.com<mailto:notifications@github.com>> 写道：


本站新帖列表及 一级板块列表内，置顶帖子会重复出现。
