### ISSUE TITLE
后台开启css压缩功能点击有时候不灵BUG

### ISSUE THREAD

**Issue by zsbox** [medz/fans#261]
![qq 20170607165039](https://user-images.githubusercontent.com/20392882/26870222-dd1d8b12-4ba1-11e7-8af3-d9b0f5c1e654.png) 版本情况
![qq 20170607165245](https://user-images.githubusercontent.com/20392882/26870237-ea821340-4ba1-11e7-879b-5b663fd43cf3.png) 点击按钮无效  有时候有效

**Comment by medz** [comment]
好的～
