### ISSUE TITLE
v1.1.0-alpha.1，有没有安装成功的？

### ISSUE THREAD

**Issue by wuyou178** [medz/fans#263]
水平低，v1.1.0-alpha.1不会用了.....
有没有详细的教程...
官方的 执行composer install后不能访问https://yousite/install.php页面

**Comment by medz** [comment]
你看的文档是 1.0 吧？文档版本选择为 1.1阅读 安装

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月9日，01:08，wuyou178 <notifications@github.com<mailto:notifications@github.com>> 写道：


水平低，v1.1.0-alpha.1不会用了.....
有没有详细的教程...
官方的 执行composer install后不能访问https://yousite/install.php页面<https://yousite/install.php%E9%A1%B5%E9%9D%A2>

**Comment by medz** [comment]
https://medz.cn 安装的是 Fans 1.1
