### ISSUE TITLE
附件上传机制

### ISSUE THREAD

**Issue by zsbox** [medz/fans#264]
目前附件上传还是用的flash 体验很不好 而且点击上传附件按钮响应时间过长 用户多半会认为没点成功 能否改用input type="file"的方式 兼容性也更好 相应也会更快吧

**Comment by medz** [comment]
这个问题会该的，在 1.1 重构完成后这个东西就会被解决～

**Comment by zsbox** [comment]
我是觉得目前功能已经够了 应该着手解决可用性问题了 只要稳定好用 相信还是有很多人支持的啊

**Comment by medz** [comment]
你理解的是 1.0 版本 1.0 版本是在 pw9 的基础上修复bug，而 1.1 版本则是完全重构的项目了，1.0 有些东西取决于 pw9，是无法更改的～

**Comment by zsbox** [comment]
嗯  我理解的是无论是1.1也好（ Laravel是个好框架）1.0也好 功能应该差不多了 够轻够快  只是细节上 稳定性上是否能再好点 相信维护者也在做这个事  我觉得目前来说 站长还是希望系统够稳定 功能以后慢慢来（这样维护者也能更省的力） 目前pw比起dz是有优势的啊 最最直接的就是 移动app开放（现在是重移动端的时代） 这个目前dz就很差 api也没开放 很多开发者想做移动端门槛太高 dz界面老化 功能多是多 但是也更难操作 最后想说 本人是做前端开发的 不才 不知道是否有幸参与到pw前端的优化
