### ISSUE TITLE
【Docker】每日一构建！回帖提交你想要的 docker 环境要求，每天选一个构建提交！

### ISSUE THREAD

**Issue by medz** [medz/fans#283]
例如，你想安装 Fans 1 但是不会安装环境！可以回帖要 Fans 1 完整的 Docker 构建。一份 docker 有 nginx、mysql、php-fpm，都是最新稳定环境！

例如2：你想体验 Fans 2 的 API，但是 PHP 环境要求太复杂不会，也可以给你构建环境！

> 不限制程序环境，非我熟悉的环境，提供需要的环境软件信息等！

构建唯一要求，Star  这个仓库（右上角✨）

构建如果是简单单一的，直接提供给你 Dockerfile 文件，如果是复杂环境，例如 LNMP 则使用 `docker compose` 进行组织！

## 构建清单

- [x] Fans 2 程序环境

**Comment by bohaokeji** [comment]
Fans 2 的 API

**Comment by medz** [comment]
@bohaokeji 按照你的要求，Fans 2 docker 支持已经添加完成！直接下载 fans 2 程序即可使用，详情请看 readme.md

**Comment by zevhack** [comment]
我想体验Fans 2，环境按照教程搭建过后 出现404，think sns 也是一样的。
