### ISSUE TITLE
/var/www/vendor/autoload.php这个文件在哪里？

### ISSUE THREAD

**Issue by ruizhaoz1** [medz/fans#284]
fans@915ba28709bb:/var/www$ php fans key:generate && php fans jwt:secret && php fans migrate --seed

Warning: require(/var/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/fans on line 21

Call Stack:
    0.0004     397944   1. {main}() /var/www/fans:0

Fatal error: require(): Failed opening required '/var/www/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/fans on line 21

Call Stack:
    0.0004     397944   1. {main}() /var/www/fans:0

**Comment by medz** [comment]
composer install


Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年9月22日，08:42，ruizhaoz1 <notifications@github.com<mailto:notifications@github.com>> 写道：


fans@915ba28709bb:/var/www$ php fans key:generate && php fans jwt:secret && php fans migrate --seed

Warning: require(/var/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/fans on line 21

Call Stack:
0.0004 397944 1. {main}() /var/www/fans:0

Fatal error: require(): Failed opening required '/var/www/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/fans on line 21

Call Stack:
0.0004 397944 1. {main}() /var/www/fans:0

**Comment by ruizhaoz1** [comment]
fans@915ba28709bb:/var/www$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 80 installs, 0 updates, 0 removals

                                                            
  [RuntimeException]                                        
  /var/www/vendor does not exist and could not be created.  
                                                            

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by ruizhaoz1** [comment]
root@zxl:~/phpwind# docker-compose build
Building mysql
Step 1/9 : FROM registry.docker-cn.com/library/mysql:5.7
 ---> 563a026a1511
Step 2/9 : LABEL maintainer="Seven Du <shiweidu@outlook.com>"
 ---> Using cache
 ---> 8c1519445094
Step 3/9 : ARG TZ=UTC
 ---> Using cache
 ---> a194f9da738c
Step 4/9 : ENV TZ ${TZ}
 ---> Using cache
 ---> 6202e265af40
Step 5/9 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Using cache
 ---> f5fb9383dcd1
Step 6/9 : RUN chown -R mysql:root /var/lib/mysql/
 ---> Using cache
 ---> 5671bce892f0
Step 7/9 : COPY my.cnf /etc/mysql/conf.d/my.cnf
 ---> Using cache
 ---> 637b7a9225ba
Step 8/9 : CMD ["mysqld"]
 ---> Using cache
 ---> ebc870d98ad2
Step 9/9 : EXPOSE 3306
 ---> Using cache
 ---> 0ac0caf8443c
Successfully built 0ac0caf8443c
Successfully tagged phpwind_mysql:latest
Building workspace
Step 1/42 : FROM registry.docker-cn.com/library/php:7.2-cli
 ---> 656f0f210b0f
Step 2/42 : LABEL maintainer="Seven Du <shiweidu@outlook.com>"
 ---> Using cache
 ---> 96b1e82476de
Step 3/42 : USER root
 ---> Using cache
 ---> f3462d70347d
Step 4/42 : ARG DOCKER_CONTAINER_PUID=1000
 ---> Using cache
 ---> 1fce4eabaa68
Step 5/42 : ENV DOCKER_CONTAINER_PUID ${DOCKER_CONTAINER_PUID}
 ---> Using cache
 ---> 11c8f2ba42e9
Step 6/42 : ARG DOCKER_CONTAINER_PGID=1000
 ---> Using cache
 ---> 39a34907338c
Step 7/42 : ENV DOCKER_CONTAINER_PGID ${DOCKER_CONTAINER_PGID}
 ---> Using cache
 ---> abf771307f91
Step 8/42 : ARG DOCKER_CONTAINER_USER=fans
 ---> Using cache
 ---> 75e23da35dad
Step 9/42 : ENV DOCKER_CONTAINER_USER ${DOCKER_CONTAINER_USER}
 ---> Using cache
 ---> ddbf021da895
Step 10/42 : ARG DOCKER_CONTAINER_GROUP=fans
 ---> Using cache
 ---> f03e89966dee
Step 11/42 : ENV DOCKER_CONTAINER_GROUP ${DOCKER_CONTAINER_GROUP}
 ---> Using cache
 ---> c08bf02c476e
Step 12/42 : RUN apt-get update -yqq &&     pecl channel-update pecl.php.net
 ---> Using cache
 ---> 86c4ba15e6c5
Step 13/42 : RUN apt-get install -y apt-utils
 ---> Using cache
 ---> 4ef974998682
Step 14/42 : RUN groupadd -g ${DOCKER_CONTAINER_PGID} ${DOCKER_CONTAINER_GROUP} &&     useradd -u ${DOCKER_CONTAINER_PUID} -g ${DOCKER_CONTAINER_GROUP} -m ${DOCKER_CONTAINER_USER} -G ${DOCKER_CONTAINER_GROUP} &&     usermod -p "*" ${DOCKER_CONTAINER_USER}
 ---> Using cache
 ---> af2f7e069a38
Step 15/42 : ARG APP_TIMEZONE=UTC
 ---> Using cache
 ---> 1c164a232371
Step 16/42 : ENV APP_TIMEZONE ${APP_TIMEZONE}
 ---> Using cache
 ---> 9bd14ba9c821
Step 17/42 : RUN ln -snf /usr/share/zoneinfo/${APP_TIMEZONE} /etc/localtime && echo ${APP_TIMEZONE} > /etc/timezone
 ---> Using cache
 ---> c76f5fa1209f
Step 18/42 : USER root
 ---> Using cache
 ---> 4ca14b7e7892
Step 19/42 : RUN apt-get install -y         libfreetype6-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng-dev
 ---> Using cache
 ---> ccb09a85cfe7
Step 20/42 : RUN docker-php-ext-install -j$(nproc) iconv
 ---> Using cache
 ---> 4a431b480ff4
Step 21/42 : RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install -j$(nproc) gd
 ---> Using cache
 ---> 60962a91cc1b
Step 22/42 : RUN apt-get install -y libxml2-dev
 ---> Using cache
 ---> 09a5fb5abbbc
Step 23/42 : RUN docker-php-ext-install soap
 ---> Using cache
 ---> 35fe4430fee6
Step 24/42 : RUN pecl install channel://pecl.php.net/mcrypt-1.0.1 	&& docker-php-ext-enable mcrypt
 ---> Using cache
 ---> feffeed4a7e4
Step 25/42 : RUN docker-php-ext-install pdo_mysql
 ---> Using cache
 ---> f3234637b4d5
Step 26/42 : RUN docker-php-ext-install zip
 ---> Using cache
 ---> 2ee2c6b063bd
Step 27/42 : RUN docker-php-ext-install mbstring
 ---> Using cache
 ---> 092babaddb79
Step 28/42 : ARG DOCKER_PHP_INSTALL_XDEBUG=false
 ---> Using cache
 ---> 303b54834e9a
Step 29/42 : RUN if [ ${DOCKER_PHP_INSTALL_XDEBUG} = true ]; then    pecl install xdebug-2.6.0     && docker-php-ext-enable xdebug ;fi
 ---> Using cache
 ---> 3baf6e859c77
Step 30/42 : RUN apt-get install -y libmemcached-dev zlib1g-dev     && pecl install memcached     && docker-php-ext-enable memcached
 ---> Using cache
 ---> 92cb45e4ba77
Step 31/42 : USER root
 ---> Using cache
 ---> 2bd37efbd3b6
Step 32/42 : RUN curl -s http://getcomposer.org/installer | php &&     echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc &&     mv composer.phar /usr/local/bin/composer
 ---> Using cache
 ---> a13af42035a7
Step 33/42 : USER root
 ---> Using cache
 ---> ab2c6b66e941
Step 34/42 : COPY ./composer.json /home/${DOCKER_CONTAINER_USER}/.composer/composer.json
 ---> Using cache
 ---> 20cac433f2fe
Step 35/42 : RUN chown -R ${DOCKER_CONTAINER_USER}:${DOCKER_CONTAINER_GROUP} /home/${DOCKER_CONTAINER_USER}/.composer
 ---> Using cache
 ---> a36aac85aa47
Step 36/42 : USER ${DOCKER_CONTAINER_USER}
 ---> Using cache
 ---> 43bad2312018
Step 37/42 : RUN composer global install
 ---> Using cache
 ---> 7f388bb9a53d
Step 38/42 : RUN composer config -g repo.packagist composer https://packagist.phpcomposer.com
 ---> Using cache
 ---> 19e62f406bbd
Step 39/42 : RUN echo "" >> ~/.bashrc &&     echo 'export PATH="~/.composer/vendor/bin:$PATH"' >> ~/.bashrc
 ---> Using cache
 ---> 74a2d941faec
Step 40/42 : USER root
 ---> Using cache
 ---> 6fa0b29ac7d8
Step 41/42 : RUN apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     rm /var/log/lastlog /var/log/faillog
 ---> Using cache
 ---> d193f3f065dd
Step 42/42 : WORKDIR /var/www
 ---> Using cache
 ---> 656a5b0d36f4
Successfully built 656a5b0d36f4
Successfully tagged phpwind_workspace:latest
Building php-fpm
Step 1/44 : FROM registry.docker-cn.com/library/php:7.2-fpm
 ---> ec07ee5bbb89
Step 2/44 : LABEL maintainer="Seven Du <shiweidu@outlook.com>"
 ---> Using cache
 ---> 70e46f5348f7
Step 3/44 : USER root
 ---> Using cache
 ---> d948d58212f0
Step 4/44 : ARG DOCKER_CONTAINER_PUID=1000
 ---> Using cache
 ---> 381080f6d9ab
Step 5/44 : ENV DOCKER_CONTAINER_PUID ${DOCKER_CONTAINER_PUID}
 ---> Using cache
 ---> 3de45432f8ab
Step 6/44 : ARG DOCKER_CONTAINER_PGID=1000
 ---> Using cache
 ---> 08d259de2dd9
Step 7/44 : ENV DOCKER_CONTAINER_PGID ${DOCKER_CONTAINER_PGID}
 ---> Using cache
 ---> cdde2942bc53
Step 8/44 : ARG DOCKER_CONTAINER_USER=fans
 ---> Using cache
 ---> 8b0349e9842e
Step 9/44 : ENV DOCKER_CONTAINER_USER ${DOCKER_CONTAINER_USER}
 ---> Using cache
 ---> 5923271999f2
Step 10/44 : ARG DOCKER_CONTAINER_GROUP=fans
 ---> Using cache
 ---> 0758088b45c1
Step 11/44 : ENV DOCKER_CONTAINER_GROUP ${DOCKER_CONTAINER_GROUP}
 ---> Using cache
 ---> c0a6bfadca1d
Step 12/44 : RUN apt-get update -yqq &&     pecl channel-update pecl.php.net
 ---> Using cache
 ---> e44ed5b8cc36
Step 13/44 : RUN apt-get install -y apt-utils
 ---> Using cache
 ---> ed55f211f284
Step 14/44 : RUN groupadd -g ${DOCKER_CONTAINER_PGID} ${DOCKER_CONTAINER_GROUP} &&     useradd -u ${DOCKER_CONTAINER_PUID} -g ${DOCKER_CONTAINER_GROUP} -m ${DOCKER_CONTAINER_USER} -G ${DOCKER_CONTAINER_GROUP} &&     usermod -p "*" ${DOCKER_CONTAINER_USER}
 ---> Using cache
 ---> b8cf35f50e8b
Step 15/44 : ARG APP_TIMEZONE=UTC
 ---> Using cache
 ---> deb481299e6b
Step 16/44 : ENV APP_TIMEZONE ${APP_TIMEZONE}
 ---> Using cache
 ---> 4447860b4e59
Step 17/44 : RUN ln -snf /usr/share/zoneinfo/${APP_TIMEZONE} /etc/localtime && echo ${APP_TIMEZONE} > /etc/timezone
 ---> Using cache
 ---> 311823396d8a
Step 18/44 : USER root
 ---> Using cache
 ---> b354f96a1bc7
Step 19/44 : RUN apt-get update && apt-get install -y         libfreetype6-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng-dev
 ---> Using cache
 ---> 4d2133fb636b
Step 20/44 : RUN docker-php-ext-install -j$(nproc) iconv
 ---> Using cache
 ---> 59d3952c680b
Step 21/44 : RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install -j$(nproc) gd
 ---> Using cache
 ---> 6a5555414014
Step 22/44 : RUN apt-get install -y libxml2-dev
 ---> Using cache
 ---> 684bd468982c
Step 23/44 : RUN docker-php-ext-install soap
 ---> Using cache
 ---> 8bfde94676e7
Step 24/44 : RUN pecl install channel://pecl.php.net/mcrypt-1.0.1 	&& docker-php-ext-enable mcrypt
 ---> Using cache
 ---> 38b5d4ed8e44
Step 25/44 : RUN docker-php-ext-install pdo_mysql
 ---> Using cache
 ---> 088c8b329fcc
Step 26/44 : RUN docker-php-ext-install zip
 ---> Using cache
 ---> f0173e6d8391
Step 27/44 : RUN docker-php-ext-install mbstring
 ---> Using cache
 ---> 89c1cc1cf4ae
Step 28/44 : ARG DOCKER_PHP_INSTALL_XDEBUG=false
 ---> Using cache
 ---> 1d4c2c1d1fd7
Step 29/44 : RUN if [ ${DOCKER_PHP_INSTALL_XDEBUG} = true ]; then     pecl install xdebug-2.6.0     && docker-php-ext-enable xdebug ;fi
 ---> Using cache
 ---> d2012618744c
Step 30/44 : COPY ./xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
 ---> Using cache
 ---> 9291bc7af343
Step 31/44 : RUN apt-get install -y libmemcached-dev zlib1g-dev
 ---> Using cache
 ---> 0a11699d6bab
Step 32/44 : RUN pecl install memcached     && docker-php-ext-enable memcached
 ---> Using cache
 ---> 65d5158f5f83
Step 33/44 : RUN docker-php-ext-install opcache
 ---> Using cache
 ---> a67b96bb2780
Step 34/44 : COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini
 ---> Using cache
 ---> 031b499a6326
Step 35/44 : COPY ./project.ini /usr/local/etc/php/conf.d/
 ---> Using cache
 ---> 38e4d1793cd7
Step 36/44 : RUN sed -i "s/date.timezone=UTC/date.timezone=${APP_TIMEZONE}/g" /usr/local/etc/php/conf.d/project.ini
 ---> Using cache
 ---> 9fffb00babb8
Step 37/44 : COPY ./www.conf /usr/local/etc/php-fpm.d/
 ---> Using cache
 ---> 97d42112b93a
Step 38/44 : RUN sed -i "s/{{USER}}/${DOCKER_CONTAINER_USER}/g" /usr/local/etc/php-fpm.d/www.conf
 ---> Using cache
 ---> 94e3b46a6a2c
Step 39/44 : RUN sed -i "s/{{GROUP}}/${DOCKER_CONTAINER_GROUP}/g" /usr/local/etc/php-fpm.d/www.conf
 ---> Using cache
 ---> df87bd69c070
Step 40/44 : USER root
 ---> Using cache
 ---> d31f4cf37748
Step 41/44 : RUN apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     rm /var/log/lastlog /var/log/faillog
 ---> Using cache
 ---> 72e17e894f86
Step 42/44 : WORKDIR /var/www
 ---> Using cache
 ---> 814cf65667f4
Step 43/44 : CMD ["php-fpm"]
 ---> Using cache
 ---> 5ad50551c113
Step 44/44 : EXPOSE 9000
 ---> Using cache
 ---> 6dbc83bb1d53
Successfully built 6dbc83bb1d53
Successfully tagged phpwind_php-fpm:latest
Building nginx
Step 1/18 : FROM registry.docker-cn.com/library/nginx:alpine
 ---> 994032453556
Step 2/18 : LABEL maintainer="Seven Du <shiweidu@outlook.com>"
 ---> Using cache
 ---> 99854aad3331
Step 3/18 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories
 ---> Using cache
 ---> 771dfafd84ea
Step 4/18 : ARG PUID=1000
 ---> Using cache
 ---> 32495c2b8620
Step 5/18 : ENV PUID ${PUID}
 ---> Using cache
 ---> 689534ba333b
Step 6/18 : ARG USERNAME=web
 ---> Using cache
 ---> cc21bf528ddd
Step 7/18 : ENV USERNAME ${USERNAME}
 ---> Using cache
 ---> 217c78de9db9
Step 8/18 : RUN rm -rf /etc/nginx/nginx.conf
 ---> Using cache
 ---> 607b7f386083
Step 9/18 : COPY ./nginx.conf /etc/nginx/
 ---> Using cache
 ---> bda19020fa72
Step 10/18 : RUN sed -i "s/{{SET_RUNTIME_USER}}/${USERNAME}/g" /etc/nginx/nginx.conf
 ---> Using cache
 ---> 21bc1793a35f
Step 11/18 : RUN apk update     && apk upgrade
 ---> Using cache
 ---> c95616a71a82
Step 12/18 : RUN apk add --no-cache bash     && adduser -D -H -u ${PUID} -s /bin/bash ${USERNAME}
 ---> Using cache
 ---> ba21aaa73d5e
Step 13/18 : RUN echo "upstream php-upstream { server php-fpm:9000; }" > /etc/nginx/conf.d/upstream.conf     && rm /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> b83095be7ce9
Step 14/18 : ARG APP_TIMEZONE=UTC
 ---> Using cache
 ---> 25517a37c319
Step 15/18 : ENV APP_TIMEZONE ${APP_TIMEZONE}
 ---> Using cache
 ---> 1d281f6cf1d9
Step 16/18 : RUN ln -snf /usr/share/zoneinfo/${APP_TIMEZONE} /etc/localtime && echo ${APP_TIMEZONE} > /etc/timezone
 ---> Using cache
 ---> 1faed9748db9
Step 17/18 : CMD ["nginx"]
 ---> Using cache
 ---> a75c759f747d
Step 18/18 : EXPOSE 80
 ---> Using cache
 ---> 8aabcc9c89e0
Successfully built 8aabcc9c89e0
Successfully tagged phpwind_nginx:latest
root@zxl:~/phpwind# docker-compose up -d
phpwind_mysql_1 is up-to-date
phpwind_php-fpm_1 is up-to-date
phpwind_workspace_1 is up-to-date
phpwind_nginx_1 is up-to-date
root@zxl:~/phpwind# docker-compose exec --user=fans workspace bash
fans@915ba28709bb:/var/www$ php fans key:generate && php fans jwt:secret && php fans migrate --seed

Warning: require(/var/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/fans on line 21

Call Stack:
    0.0006     397784   1. {main}() /var/www/fans:0


Fatal error: require(): Failed opening required '/var/www/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/fans on line 21

Call Stack:
    0.0006     397784   1. {main}() /var/www/fans:0

fans@915ba28709bb:/var/www$
