### ISSUE TITLE
希望把語言全部拆開來讓別人也能為phpwind作翻譯。

### ISSUE THREAD

**Issue by LiMoon** [medz/fans#36]
我知道 phpwind 原本已經設計 language 的對應了，但有很多地方例如部分檔案是仍留存在 程式碼裡面而非獨立在 src/i18n 資料夾內的，之前嘗試過自己將 zh_cn 改成 zh_tw 在全面改部分語言為正體中文，仍然在論壇上有看到許多簡體字。

例如template內找到的其中幾個模板都沒有歸類放在 src/i18n 在內，但想把 template 的語言歸類放入 src/i18n 但不知道 單純的 html 語法要如何將 「return new PwError('BBS:forum.unite.error.fid.exists.not');」這種i18n語言放入 template。

如果能指點如何將這 template 的 lang 作個 拆開整合在 i18n ，我覺得日後要維護語言更新會比較不會複雜。

**Comment by medz** [comment]
好的，有时间就做。

Seven Du <lovevipdsw@outlook.com<mailto:lovevipdsw@outlook.com>>

在 2016年11月11日，00:57，LiMoon <notifications@github.com<mailto:notifications@github.com>> 写道：


我知道 phpwind 原本已經設計 language 的對應了，但有很多地方例如部分檔案是仍留存在 程式碼裡面而非獨立在 language 資料夾內的，之前嘗試過自己將 zh_cn 改成 zh_tw 在全面改部分語言為正體中文，仍然在論壇上有看到許多簡體字。

**Comment by LiMoon** [comment]
請問有沒有教學能讓我可以方便幫忙改呢？
畢竟看現有的部分元件真的滿龐大的

**Comment by medz** [comment]
@LiMoon 目前没用教学~只能凭借扎实的语言基础对程序修改咯~。

**Comment by LiMoon** [comment]
因為 template 裡面的 資源不知道要怎麼 引入 src/i81n 的資源，
有沒有相關phpwind他的內置語法？

例如是 什麼語法能讓他引入lang的資源？

**Comment by kinosang** [comment]
+1

i18n 十分必要

**Comment by medz** [comment]
整体构建会慢慢修改～开始开发前后端分离的时候会增加多语言支持～

**Comment by guoqiang5277** [comment]
最好前期设计的时候，就把框架给设计成多语言模式的。
