### ISSUE TITLE
必须设置域名建议

### ISSUE THREAD

**Issue by lkddi** [medz/fans#54]
现在论坛，必须设置域名，比如我有多个域名。其他域名可以访问到首页，但是点击任意连接就回转到后台设置的域名上。
最好支持不用绑定域名，即可各自域名访问而不跳转域名。

**Comment by zhanlanzhiyu** [comment]
感觉不大清楚

**Comment by medz** [comment]
域名信息设置就是当前域名～

**Comment by chenjx323** [comment]
嗯 可以说明白点吗？

**Comment by likeclub** [comment]
他的意思希望增加绑定多个域名，不修改站点链接！

**Comment by medz** [comment]
哦哦～懂了～懂了～这个任重道远呀～pw以前吧很多链接直接生成完整储存在数据库了～修改起来确实恼火～ 等待下吧～前后端和app做完～慢慢弱化pw的域名绑定，让程序不需要绑定任何域名情况
