### ISSUE TITLE
表情不按照规则排序

### ISSUE THREAD

**Issue by ghost** [medz/fans#71]
在后台添加的表情没有按照文件名进行排序（自带的那个淘公仔也被打乱了），完全被打乱了顺序。强迫症简直不能忍啊！！！
在数据库中，默认的淘公仔是ID跟文件名对应的（即ID1，同时对应1.gif）。
然而，新添加的表情就乱了：ID跟文件名（都是数字123456……这样的）不对应，完全乱了。
这应该是个排序的BUG。。。
**在PHPWind 9.0中没有这个问题。**

**Comment by medz** [comment]
你是希望排列按照文件名顺序吗？这样就和文件系统不匹配咯～
