### ISSUE TITLE
后台邮件功能优化请求

### ISSUE THREAD

**Issue by andy1247008998** [medz/fans#92]
后台——全局——电子邮件
希望：
* [ ] 添加一个独立的SSL开关，而不是手写ssl://
* [ ] 提供更好的错误主动检测和错误信息提示
* [ ] 电子邮件检测中记住“收件人地址”，避免反复输入浪费时间
* [ ] 为国内常用企业邮箱如腾讯企业邮箱、阿里云企业邮箱等提供默认配置建议

**Comment by medz** [comment]
已经调整issue格式～请关注与本条issue关联的commit～
