### ISSUE TITLE
附件url格式自定义请求

### ISSUE THREAD

**Issue by andy1247008998** [medz/fans#94]
举例：
假设pw主站域名为www.example.com，

首先将附件分离到独立域名如pics.example.com，如图片
https://pics.example.com/attachment/1702/thread/abc.jpg
pics.example.com指向CDN图床，可实现图片CDN加速。

然后，为了使用CDN提供的水印功能，需要添加参数，如：
https://pics.example.com/attachment/1702/thread/abc.jpg!watermark

此功能目前只能通过修改pw内部文件才可实现，如果单独提出来做成一个功能，可方便站长们轻松实现CDN加速。

**Comment by medz** [comment]
附件分离，目前在pw的架构中不是很好实现～争取吧～
